// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::borrow_as_ptr,
    clippy::missing_transmute_annotations,
    clippy::ptr_as_ptr,
    clippy::transmute_ptr_to_ptr,
    clippy::useless_transmute,
    reason = "generated windows-bindgen output"
)]

pub struct ActivationRegistrationManager;
impl ActivationRegistrationManager {
    pub fn RegisterForFileTypeActivation(
        supportedfiletypes: &[windows_core::HSTRING],
        logo: &windows_core::HSTRING,
        displayname: &windows_core::HSTRING,
        supportedverbs: &[windows_core::HSTRING],
        exepath: &windows_core::HSTRING,
    ) -> windows_core::Result<()> {
        Self::IActivationRegistrationManagerStatics(|this| unsafe {
            (windows_core::Interface::vtable(this).RegisterForFileTypeActivation)(
                windows_core::Interface::as_raw(this),
                supportedfiletypes.len().try_into().unwrap(),
                core::mem::transmute(supportedfiletypes.as_ptr()),
                core::mem::transmute_copy(logo),
                core::mem::transmute_copy(displayname),
                supportedverbs.len().try_into().unwrap(),
                core::mem::transmute(supportedverbs.as_ptr()),
                core::mem::transmute_copy(exepath),
            )
            .ok()
        })
    }
    pub fn RegisterForProtocolActivation(
        scheme: &windows_core::HSTRING,
        logo: &windows_core::HSTRING,
        displayname: &windows_core::HSTRING,
        exepath: &windows_core::HSTRING,
    ) -> windows_core::Result<()> {
        Self::IActivationRegistrationManagerStatics(|this| unsafe {
            (windows_core::Interface::vtable(this).RegisterForProtocolActivation)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(scheme),
                core::mem::transmute_copy(logo),
                core::mem::transmute_copy(displayname),
                core::mem::transmute_copy(exepath),
            )
            .ok()
        })
    }
    pub fn RegisterForStartupActivation(
        taskid: &windows_core::HSTRING,
        exepath: &windows_core::HSTRING,
    ) -> windows_core::Result<()> {
        Self::IActivationRegistrationManagerStatics(|this| unsafe {
            (windows_core::Interface::vtable(this).RegisterForStartupActivation)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(taskid),
                core::mem::transmute_copy(exepath),
            )
            .ok()
        })
    }
    pub fn UnregisterForFileTypeActivation(
        filetypes: &[windows_core::HSTRING],
        exepath: &windows_core::HSTRING,
    ) -> windows_core::Result<()> {
        Self::IActivationRegistrationManagerStatics(|this| unsafe {
            (windows_core::Interface::vtable(this).UnregisterForFileTypeActivation)(
                windows_core::Interface::as_raw(this),
                filetypes.len().try_into().unwrap(),
                core::mem::transmute(filetypes.as_ptr()),
                core::mem::transmute_copy(exepath),
            )
            .ok()
        })
    }
    pub fn UnregisterForProtocolActivation(
        scheme: &windows_core::HSTRING,
        exepath: &windows_core::HSTRING,
    ) -> windows_core::Result<()> {
        Self::IActivationRegistrationManagerStatics(|this| unsafe {
            (windows_core::Interface::vtable(this).UnregisterForProtocolActivation)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(scheme),
                core::mem::transmute_copy(exepath),
            )
            .ok()
        })
    }
    pub fn UnregisterForStartupActivation(
        taskid: &windows_core::HSTRING,
    ) -> windows_core::Result<()> {
        Self::IActivationRegistrationManagerStatics(|this| unsafe {
            (windows_core::Interface::vtable(this).UnregisterForStartupActivation)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(taskid),
            )
            .ok()
        })
    }
    fn IActivationRegistrationManagerStatics<
        R,
        F: FnOnce(&IActivationRegistrationManagerStatics) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            ActivationRegistrationManager,
            IActivationRegistrationManagerStatics,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeName for ActivationRegistrationManager {
    const NAME: &'static str = "Microsoft.Windows.AppLifecycle.ActivationRegistrationManager";
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AppActivationArguments(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    AppActivationArguments,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl AppActivationArguments {
    pub fn Kind(&self) -> windows_core::Result<ExtendedActivationKind> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Kind)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn Data(&self) -> windows_core::Result<windows_core::IInspectable> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Data)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
}
impl windows_core::RuntimeType for AppActivationArguments {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IAppActivationArguments>();
}
unsafe impl windows_core::Interface for AppActivationArguments {
    type Vtable = <IAppActivationArguments as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IAppActivationArguments as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for AppActivationArguments {
    const NAME: &'static str = "Microsoft.Windows.AppLifecycle.AppActivationArguments";
}
unsafe impl Send for AppActivationArguments {}
unsafe impl Sync for AppActivationArguments {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AppInstance(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    AppInstance,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl AppInstance {
    pub fn UnregisterKey(&self) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).UnregisterKey)(windows_core::Interface::as_raw(
                this,
            ))
            .ok()
        }
    }
    pub fn RedirectActivationToAsync<P0>(
        &self,
        args: P0,
    ) -> windows_core::Result<windows_future::IAsyncAction>
    where
        P0: windows_core::Param<AppActivationArguments>,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RedirectActivationToAsync)(
                windows_core::Interface::as_raw(this),
                args.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn GetActivatedEventArgs(&self) -> windows_core::Result<AppActivationArguments> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetActivatedEventArgs)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn Activated<P0>(&self, handler: P0) -> windows_core::Result<i64>
    where
        P0: windows_core::Param<windows::Foundation::EventHandler<AppActivationArguments>>,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Activated)(
                windows_core::Interface::as_raw(this),
                handler.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveActivated(&self, token: i64) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveActivated)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    pub fn Key(&self) -> windows_core::Result<windows_core::HSTRING> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Key)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn IsCurrent(&self) -> windows_core::Result<bool> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsCurrent)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn ProcessId(&self) -> windows_core::Result<u32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ProcessId)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn GetCurrent() -> windows_core::Result<AppInstance> {
        Self::IAppInstanceStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetCurrent)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn GetInstances() -> windows_core::Result<windows_collections::IVector<AppInstance>> {
        Self::IAppInstanceStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetInstances)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn FindOrRegisterForKey(key: &windows_core::HSTRING) -> windows_core::Result<AppInstance> {
        Self::IAppInstanceStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).FindOrRegisterForKey)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(key),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn Restart(
        arguments: &windows_core::HSTRING,
    ) -> windows_core::Result<windows::ApplicationModel::Core::AppRestartFailureReason> {
        Self::IAppInstanceStatics2(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Restart)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(arguments),
                &mut result__,
            )
            .map(|| result__)
        })
    }
    fn IAppInstanceStatics<R, F: FnOnce(&IAppInstanceStatics) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<AppInstance, IAppInstanceStatics> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
    fn IAppInstanceStatics2<R, F: FnOnce(&IAppInstanceStatics2) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<AppInstance, IAppInstanceStatics2> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for AppInstance {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IAppInstance>();
}
unsafe impl windows_core::Interface for AppInstance {
    type Vtable = <IAppInstance as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IAppInstance as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for AppInstance {
    const NAME: &'static str = "Microsoft.Windows.AppLifecycle.AppInstance";
}
unsafe impl Send for AppInstance {}
unsafe impl Sync for AppInstance {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ExtendedActivationKind(pub i32);
impl ExtendedActivationKind {
    pub const Launch: Self = Self(0i32);
    pub const Search: Self = Self(1i32);
    pub const ShareTarget: Self = Self(2i32);
    pub const File: Self = Self(3i32);
    pub const Protocol: Self = Self(4i32);
    pub const FileOpenPicker: Self = Self(5i32);
    pub const FileSavePicker: Self = Self(6i32);
    pub const CachedFileUpdater: Self = Self(7i32);
    pub const ContactPicker: Self = Self(8i32);
    pub const Device: Self = Self(9i32);
    pub const PrintTaskSettings: Self = Self(10i32);
    pub const CameraSettings: Self = Self(11i32);
    pub const RestrictedLaunch: Self = Self(12i32);
    pub const AppointmentsProvider: Self = Self(13i32);
    pub const Contact: Self = Self(14i32);
    pub const LockScreenCall: Self = Self(15i32);
    pub const VoiceCommand: Self = Self(16i32);
    pub const LockScreen: Self = Self(17i32);
    pub const PickerReturned: Self = Self(1000i32);
    pub const WalletAction: Self = Self(1001i32);
    pub const PickFileContinuation: Self = Self(1002i32);
    pub const PickSaveFileContinuation: Self = Self(1003i32);
    pub const PickFolderContinuation: Self = Self(1004i32);
    pub const WebAuthenticationBrokerContinuation: Self = Self(1005i32);
    pub const WebAccountProvider: Self = Self(1006i32);
    pub const ComponentUI: Self = Self(1007i32);
    pub const ProtocolForResults: Self = Self(1009i32);
    pub const ToastNotification: Self = Self(1010i32);
    pub const Print3DWorkflow: Self = Self(1011i32);
    pub const DialReceiver: Self = Self(1012i32);
    pub const DevicePairing: Self = Self(1013i32);
    pub const UserDataAccountsProvider: Self = Self(1014i32);
    pub const FilePickerExperience: Self = Self(1015i32);
    pub const LockScreenComponent: Self = Self(1016i32);
    pub const ContactPanel: Self = Self(1017i32);
    pub const PrintWorkflowForegroundTask: Self = Self(1018i32);
    pub const GameUIProvider: Self = Self(1019i32);
    pub const StartupTask: Self = Self(1020i32);
    pub const CommandLineLaunch: Self = Self(1021i32);
    pub const BarcodeScannerProvider: Self = Self(1022i32);
    pub const PrintSupportJobUI: Self = Self(1023i32);
    pub const PrintSupportSettingsUI: Self = Self(1024i32);
    pub const PhoneCallActivation: Self = Self(1025i32);
    pub const VpnForeground: Self = Self(1026i32);
    pub const Push: Self = Self(5000i32);
    pub const AppNotification: Self = Self(5001i32);
}
impl windows_core::TypeKind for ExtendedActivationKind {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for ExtendedActivationKind {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.Windows.AppLifecycle.ExtendedActivationKind;i4)",
    );
}
windows_core::imp::define_interface!(
    IActivationRegistrationManagerStatics,
    IActivationRegistrationManagerStatics_Vtbl,
    0x5ac4e92e_017b_5d68_8198_f68636ab99d3
);
impl windows_core::RuntimeType for IActivationRegistrationManagerStatics {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IActivationRegistrationManagerStatics_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub RegisterForFileTypeActivation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        u32,
        *const windows_core::HSTRING,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        u32,
        *const windows_core::HSTRING,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub RegisterForProtocolActivation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub RegisterForStartupActivation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub UnregisterForFileTypeActivation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        u32,
        *const windows_core::HSTRING,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub UnregisterForProtocolActivation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub UnregisterForStartupActivation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IAppActivationArguments,
    IAppActivationArguments_Vtbl,
    0x14f99eaf_1580_5062_bdc8_d5d1c31138fb
);
impl windows_core::RuntimeType for IAppActivationArguments {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IAppActivationArguments_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Kind: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut ExtendedActivationKind,
    ) -> windows_core::HRESULT,
    pub Data: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IAppInstance,
    IAppInstance_Vtbl,
    0x75766ae4_0239_5a26_b9da_d5bfc75a4866
);
impl windows_core::RuntimeType for IAppInstance {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IAppInstance_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub UnregisterKey: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
    pub RedirectActivationToAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub GetActivatedEventArgs: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub Activated: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut i64,
    ) -> windows_core::HRESULT,
    pub RemoveActivated:
        unsafe extern "system" fn(*mut core::ffi::c_void, i64) -> windows_core::HRESULT,
    pub Key: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub IsCurrent:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
    pub ProcessId:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IAppInstanceStatics,
    IAppInstanceStatics_Vtbl,
    0x4f414b25_8330_5a9b_bbc1_8229d479649d
);
impl windows_core::RuntimeType for IAppInstanceStatics {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IAppInstanceStatics_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub GetCurrent: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub GetInstances: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub FindOrRegisterForKey: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IAppInstanceStatics2,
    IAppInstanceStatics2_Vtbl,
    0xfe9f1885_7160_5397_ba9b_5890b24fdc04
);
impl windows_core::RuntimeType for IAppInstanceStatics2 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IAppInstanceStatics2_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Restart: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut windows::ApplicationModel::Core::AppRestartFailureReason,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IPushNotificationChannel,
    IPushNotificationChannel_Vtbl,
    0xda28bbcb_7695_5d38_af82_f30b72fef1f6
);
impl windows_core::RuntimeType for IPushNotificationChannel {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IPushNotificationChannel_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Uri: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub ExpirationTime: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows::Foundation::DateTime,
    ) -> windows_core::HRESULT,
    pub Close: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IPushNotificationCreateChannelResult,
    IPushNotificationCreateChannelResult_Vtbl,
    0x4df3717f_5d33_56e9_b381_1b350c95722e
);
impl windows_core::RuntimeType for IPushNotificationCreateChannelResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IPushNotificationCreateChannelResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Channel: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub ExtendedError: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows_core::HRESULT,
    ) -> windows_core::HRESULT,
    pub Status: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut PushNotificationChannelStatus,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IPushNotificationManager,
    IPushNotificationManager_Vtbl,
    0x902f4aba_ff63_5dfe_a88f_15cc6bed55ff
);
impl windows_core::RuntimeType for IPushNotificationManager {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IPushNotificationManager_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Register: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
    pub Unregister: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
    pub UnregisterAll: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
    pub CreateChannelAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        windows_core::GUID,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub PushReceived: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut i64,
    ) -> windows_core::HRESULT,
    pub RemovePushReceived:
        unsafe extern "system" fn(*mut core::ffi::c_void, i64) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IPushNotificationManagerStatics,
    IPushNotificationManagerStatics_Vtbl,
    0x71329470_1b55_58dc_a00c_68c26f2d8bd9
);
impl windows_core::RuntimeType for IPushNotificationManagerStatics {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IPushNotificationManagerStatics_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub IsSupported:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
    pub Default: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IPushNotificationReceivedEventArgs,
    IPushNotificationReceivedEventArgs_Vtbl,
    0xfbd4ec53_bb83_5495_8777_d3cf13e4299c
);
impl windows_core::RuntimeType for IPushNotificationReceivedEventArgs {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IPushNotificationReceivedEventArgs_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Payload: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut u32,
        *mut *mut u8,
    ) -> windows_core::HRESULT,
    pub GetDeferral: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub Canceled: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut i64,
    ) -> windows_core::HRESULT,
    pub RemoveCanceled:
        unsafe extern "system" fn(*mut core::ffi::c_void, i64) -> windows_core::HRESULT,
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PushNotificationChannel(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    PushNotificationChannel,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl PushNotificationChannel {
    pub fn Uri(&self) -> windows_core::Result<windows::Foundation::Uri> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Uri)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn ExpirationTime(&self) -> windows_core::Result<windows::Foundation::DateTime> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ExpirationTime)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn Close(&self) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this))
                .ok()
        }
    }
}
impl windows_core::RuntimeType for PushNotificationChannel {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IPushNotificationChannel>();
}
unsafe impl windows_core::Interface for PushNotificationChannel {
    type Vtable = <IPushNotificationChannel as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IPushNotificationChannel as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for PushNotificationChannel {
    const NAME: &'static str = "Microsoft.Windows.PushNotifications.PushNotificationChannel";
}
unsafe impl Send for PushNotificationChannel {}
unsafe impl Sync for PushNotificationChannel {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct PushNotificationChannelStatus(pub i32);
impl PushNotificationChannelStatus {
    pub const InProgress: Self = Self(0i32);
    pub const InProgressRetry: Self = Self(1i32);
    pub const CompletedSuccess: Self = Self(2i32);
    pub const CompletedFailure: Self = Self(3i32);
}
impl windows_core::TypeKind for PushNotificationChannelStatus {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for PushNotificationChannelStatus {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.Windows.PushNotifications.PushNotificationChannelStatus;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PushNotificationCreateChannelResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    PushNotificationCreateChannelResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl PushNotificationCreateChannelResult {
    pub fn Channel(&self) -> windows_core::Result<PushNotificationChannel> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Channel)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn ExtendedError(&self) -> windows_core::Result<windows_core::HRESULT> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ExtendedError)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn Status(&self) -> windows_core::Result<PushNotificationChannelStatus> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Status)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeType for PushNotificationCreateChannelResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IPushNotificationCreateChannelResult>();
}
unsafe impl windows_core::Interface for PushNotificationCreateChannelResult {
    type Vtable = <IPushNotificationCreateChannelResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID =
        <IPushNotificationCreateChannelResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for PushNotificationCreateChannelResult {
    const NAME: &'static str =
        "Microsoft.Windows.PushNotifications.PushNotificationCreateChannelResult";
}
unsafe impl Send for PushNotificationCreateChannelResult {}
unsafe impl Sync for PushNotificationCreateChannelResult {}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct PushNotificationCreateChannelStatus {
    pub status: PushNotificationChannelStatus,
    pub extendedError: windows_core::HRESULT,
    pub retryCount: u32,
}
impl windows_core::TypeKind for PushNotificationCreateChannelStatus {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for PushNotificationCreateChannelStatus {
    const SIGNATURE :windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice ( b"struct(Microsoft.Windows.PushNotifications.PushNotificationCreateChannelStatus;enum(Microsoft.Windows.PushNotifications.PushNotificationChannelStatus;i4);struct(Windows.Foundation.HResult;i4);u4)" ) ;
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PushNotificationManager(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    PushNotificationManager,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl PushNotificationManager {
    pub fn Register(&self) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).Register)(windows_core::Interface::as_raw(this))
                .ok()
        }
    }
    pub fn Unregister(&self) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).Unregister)(windows_core::Interface::as_raw(
                this,
            ))
            .ok()
        }
    }
    pub fn UnregisterAll(&self) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).UnregisterAll)(windows_core::Interface::as_raw(
                this,
            ))
            .ok()
        }
    }
    pub fn CreateChannelAsync(
        &self,
        remoteid: windows_core::GUID,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            PushNotificationCreateChannelResult,
            PushNotificationCreateChannelStatus,
        >,
    > {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateChannelAsync)(
                windows_core::Interface::as_raw(this),
                remoteid,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn PushReceived<P0>(&self, handler: P0) -> windows_core::Result<i64>
    where
        P0: windows_core::Param<
                windows::Foundation::TypedEventHandler<
                    PushNotificationManager,
                    PushNotificationReceivedEventArgs,
                >,
            >,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).PushReceived)(
                windows_core::Interface::as_raw(this),
                handler.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemovePushReceived(&self, token: i64) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).RemovePushReceived)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    pub fn IsSupported() -> windows_core::Result<bool> {
        Self::IPushNotificationManagerStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsSupported)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        })
    }
    pub fn Default() -> windows_core::Result<PushNotificationManager> {
        Self::IPushNotificationManagerStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Default)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn IPushNotificationManagerStatics<
        R,
        F: FnOnce(&IPushNotificationManagerStatics) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            PushNotificationManager,
            IPushNotificationManagerStatics,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for PushNotificationManager {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IPushNotificationManager>();
}
unsafe impl windows_core::Interface for PushNotificationManager {
    type Vtable = <IPushNotificationManager as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IPushNotificationManager as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for PushNotificationManager {
    const NAME: &'static str = "Microsoft.Windows.PushNotifications.PushNotificationManager";
}
unsafe impl Send for PushNotificationManager {}
unsafe impl Sync for PushNotificationManager {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PushNotificationReceivedEventArgs(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    PushNotificationReceivedEventArgs,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl PushNotificationReceivedEventArgs {
    pub fn Payload(&self) -> windows_core::Result<windows_core::Array<u8>> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::MaybeUninit::zeroed();
            (windows_core::Interface::vtable(this).Payload)(
                windows_core::Interface::as_raw(this),
                windows_core::Array::<u8>::set_abi_len(core::mem::transmute(&mut result__)),
                result__.as_mut_ptr() as *mut _ as _,
            )
            .map(|| result__.assume_init())
        }
    }
    pub fn GetDeferral(
        &self,
    ) -> windows_core::Result<windows::ApplicationModel::Background::BackgroundTaskDeferral> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetDeferral)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn Canceled<P0>(&self, handler: P0) -> windows_core::Result<i64>
    where
        P0: windows_core::Param<
                windows::ApplicationModel::Background::BackgroundTaskCanceledEventHandler,
            >,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Canceled)(
                windows_core::Interface::as_raw(this),
                handler.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveCanceled(&self, token: i64) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveCanceled)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
}
impl windows_core::RuntimeType for PushNotificationReceivedEventArgs {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IPushNotificationReceivedEventArgs>();
}
unsafe impl windows_core::Interface for PushNotificationReceivedEventArgs {
    type Vtable = <IPushNotificationReceivedEventArgs as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID =
        <IPushNotificationReceivedEventArgs as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for PushNotificationReceivedEventArgs {
    const NAME: &'static str =
        "Microsoft.Windows.PushNotifications.PushNotificationReceivedEventArgs";
}
unsafe impl Send for PushNotificationReceivedEventArgs {}
unsafe impl Sync for PushNotificationReceivedEventArgs {}
